-   id: prettier
    name: Prettier
    description: This hook runs Prettier on JavaScript files
    entry: prettier
    language: node
    files: '\.jsx?$'
    exclude: 'node_modules'
    types: [text]
    args: ['--write', '--no-bracket-spacing', '--single-quote', '--print-width=90', 'jsx-bracket-same-line']
-   id: eslint
    name: eslint
    description: This hook runs Preeslintttier on JavaScript files
    entry: eslint
    language: node
    files: '\.jsx?$'
    exclude: 'node_modules'
    types: [text]
